/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.4 */
/* Sat Dec 16 15:59:00 2023 */

/* parameterized module instance */
debuggerTestsROM __ (.Address( ), .OutClock( ), .OutClockEn( ), 
    .Reset( ), .Q( ));
