/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.4 */
/* Sun Dec 17 13:01:11 2023 */

/* parameterized module instance */
debuggerTestsROM __ (.Address( ), .OutClock( ), .OutClockEn( ), 
    .Reset( ), .Q( ));
