

// TOOL:     vlog2tf
// DATE:     Sun Oct 15 15:19:41 2023
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   core
// DESIGN:   core
// FILENAME: core_tf.v
// PROJECT:  ForthCPU
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module core_tf();

// Inputs
    reg CLK;
    reg RESET;
    reg [15:0] DIN;
    reg INT0;
    reg INT1;


// Outputs
    wire FETCH;
    wire DECODE;
    wire EXECUTE;
    wire COMMIT;
    wire [15:0] ADDR_BUF;
    wire [15:0] DOUT_BUF;
    wire RDN_BUF;
    wire ABUS_OEN;
    wire DBUS_OEN;
    wire WRN0_BUF;
    wire WRN1_BUF;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    core UUT (
        .CLK(CLK), 
        .RESET(RESET), 
        .FETCH(FETCH), 
        .DECODE(DECODE), 
        .EXECUTE(EXECUTE), 
        .COMMIT(COMMIT), 
        .ADDR_BUF(ADDR_BUF), 
        .DOUT_BUF(DOUT_BUF), 
        .DIN(DIN), 
        .INT0(INT0), 
        .INT1(INT1), 
        .RDN_BUF(RDN_BUF), 
        .ABUS_OEN(ABUS_OEN), 
        .DBUS_OEN(DBUS_OEN), 
        .WRN0_BUF(WRN0_BUF), 
        .WRN1_BUF(WRN1_BUF)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            CLK = 0;
            RESET = 0;
            DIN = 0;
            INT0 = 0;
            INT1 = 0;
    end

endmodule // core_tf