/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.7 */
/* Tue Sep 12 18:06:20 2023 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ), .CLKOS2( ), .CLKOS3( ), .LOCK( ));
