/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 3.9 */
/* Wed Oct 25 15:12:16 2023 */

/* parameterized module instance */
ram __ (.Address( ), .Data( ), .Clock( ), .WE( ), .ClockEn( ), .Q( ));
