/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 2.8 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n rom -lang verilog -synth synplify -bus_exp 7 -bb -arch xo3c00a -type rom -addr_width 7 -num_rows 128 -data_width 16 -outdata UNREGISTERED -memfile c:/users/duncan/git/forthcpu/bootrom/source/blink.mem -memformat orca  */
/* Fri Nov 03 17:18:46 2023 */


`timescale 1 ns / 1 ps
module rom (Address, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [6:0] Address;
    output wire [15:0] Q;


    defparam mem_0_15.initval = 128'h00000001555011000001551404044111 ;
    ROM128X1A mem_0_15 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[15]));

    defparam mem_0_14.initval = 128'h00000000451555441450455515111000 ;
    ROM128X1A mem_0_14 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[14]));

    defparam mem_0_13.initval = 128'h00000000514011005550510004004000 ;
    ROM128X1A mem_0_13 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[13]));

    defparam mem_0_12.initval = 128'h00000000511111000000504004140000 ;
    ROM128X1A mem_0_12 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[12]));

    defparam mem_0_11.initval = 128'h00000000450151011440450004044000 ;
    ROM128X1A mem_0_11 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[11]));

    defparam mem_0_10.initval = 128'h00000000411011011450400004000000 ;
    ROM128X1A mem_0_10 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[10]));

    defparam mem_0_9.initval = 128'h00000001514051000401500004004111 ;
    ROM128X1A mem_0_9 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[9]));

    defparam mem_0_8.initval = 128'h00000000555015454410550515451111 ;
    ROM128X1A mem_0_8 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[8]));

    defparam mem_0_7.initval = 128'h00000000411411000001400404054000 ;
    ROM128X1A mem_0_7 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[7]));

    defparam mem_0_6.initval = 128'h00000000450155445554400004000000 ;
    ROM128X1A mem_0_6 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[6]));

    defparam mem_0_5.initval = 128'h00000004410155015540441014014000 ;
    ROM128X1A mem_0_5 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[5]));

    defparam mem_0_4.initval = 128'h00000000410004401400441005040444 ;
    ROM128X1A mem_0_4 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[4]));

    defparam mem_0_3.initval = 128'h00000000010040100150400000144004 ;
    ROM128X1A mem_0_3 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[3]));

    defparam mem_0_2.initval = 128'h00000004011540104540400000000040 ;
    ROM128X1A mem_0_2 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[2]));

    defparam mem_0_1.initval = 128'h00000000400441101504401444104000 ;
    ROM128X1A mem_0_1 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[1]));

    defparam mem_0_0.initval = 128'h00000000040540000500054400040000 ;
    ROM128X1A mem_0_0 (.AD6(Address[6]), .AD5(Address[5]), .AD4(Address[4]), 
        .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), .AD0(Address[0]), 
        .DO0(Q[0]));



    // exemplar begin
    // exemplar end

endmodule
