/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 2.8 */
/* Fri Nov 10 15:57:07 2023 */

/* parameterized module instance */
rom __ (.Address( ), .Q( ));
