/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 2.8 */
/* Mon Nov 13 18:42:28 2023 */

/* parameterized module instance */
rom __ (.Address( ), .Q( ));
