/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 7.5 */
/* Wed Oct 25 16:18:23 2023 */

/* parameterized module instance */
RAM __ (.Clock( ), .ClockEn( ), .Reset( ), .ByteEn( ), .WE( ), 
    .Address( ), .Data( ), .Q( ));
