/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 7.5 */
/* Sun Nov 12 15:44:00 2023 */

/* parameterized module instance */
RAM __ (.Clock( ), .ClockEn( ), .Reset( ), .ByteEn( ), .WE( ), 
    .Address( ), .Data( ), .Q( ));
