/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 7.5 */
/* Sun Oct 01 14:09:42 2023 */

/* parameterized module instance */
registers __ (.DataInA( ), .DataInB( ), .ByteEnA( ), .ByteEnB( ), 
    .AddressA( ), .AddressB( ), .ClockA( ), .ClockB( ), .ClockEnA( ), 
    .ClockEnB( ), .WrA( ), .WrB( ), .ResetA( ), .ResetB( ), .QA( ), 
    .QB( ));
